# Generated by Django 3.1.5 on 2021-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('stdNumber', models.IntegerField()),
                ('teacher', models.CharField(choices=[('teacher 1', 'Teacher 1'), ('teacher 2', 'Teacher 2'), ('teacher 3', 'Teacher 3')], max_length=9)),
            ],
        ),
    ]
